// Build step: validates data/trip.json, hashes SITE_PASSWORD from the
// environment into generated/site-config.js (gitignored, regenerated every
// build), and templates the <head> of index.html with the trip's title,
// description, and favicon between the TRIP_HEAD marker comments.
//
// This is the script Vercel should run as the "Build Command", and the
// script `npm run dev` runs before serving locally.
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import 'dotenv/config';
import { validateTrip } from './validate.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

const DEFAULT_DEMO_PASSWORD = 'demo';

function buildPasswordHash() {
  const password = process.env.SITE_PASSWORD;
  if (!password) {
    console.warn(
      `⚠️  SITE_PASSWORD is not set — using the default demo password "${DEFAULT_DEMO_PASSWORD}".\n` +
        '   Set SITE_PASSWORD in .env (copy .env.example) before deploying for real.'
    );
  }
  return createHash('sha256')
    .update(password || DEFAULT_DEMO_PASSWORD)
    .digest('hex');
}

function writeGeneratedConfig(passwordHash) {
  mkdirSync(path.join(root, 'generated'), { recursive: true });
  const contents = `// Auto-generated by scripts/build.js — do not edit, do not commit.\nwindow.__SITE_PASSWORD_HASH__ = ${JSON.stringify(passwordHash)};\n`;
  writeFileSync(path.join(root, 'generated/site-config.js'), contents);
}

function escapeHtml(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function templateHead(trip) {
  const indexPath = path.join(root, 'index.html');
  const html = readFileSync(indexPath, 'utf8');

  const favicon = trip.site.favicon || '🧭';
  const title = escapeHtml(trip.site.title);
  const description = escapeHtml(trip.site.description);

  const block = [
    `  <title>${title}</title>`,
    `  <meta name="description" content="${description}">`,
    `  <link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>${favicon}</text></svg>">`
  ].join('\n');

  const marked = html.replace(
    /<!-- TRIP_HEAD:START -->[\s\S]*?<!-- TRIP_HEAD:END -->/,
    `<!-- TRIP_HEAD:START -->\n${block}\n  <!-- TRIP_HEAD:END -->`
  );

  if (marked === html && !html.includes('TRIP_HEAD:START')) {
    throw new Error('index.html is missing the <!-- TRIP_HEAD:START/END --> markers.');
  }

  writeFileSync(indexPath, marked);
}

function main() {
  const trip = validateTrip();
  const passwordHash = buildPasswordHash();
  writeGeneratedConfig(passwordHash);
  templateHead(trip);
  console.log('✅ Build complete: validated data/trip.json, wrote generated/site-config.js, templated index.html <head>.');
}

main();
